cloud:
    aws:
        credentials:
            accessKey: ${AWS_ACCESS_KEY}
            secretKey: ${AWS_SECRET_KEY}
        region:
            static: eu-central-1

storage:
    bucket:
        name: ${AWS_BUCKET_NAME}