cloud:
    aws:
        credentials:
            accessKey: ${AWS_ACCESS_KEY}
            secretKey: ${AWS_SECRET_KEY}
        region:
            static: ${AWS_REGION} 

storage:
    bucket:
        name: ${AWS_BUCKET_NAME}

spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}